This class uses the integral kernel to make DP predictions

In [14]:
import dp4gp_datasets
import dp4gp
import random
import numpy as np
import GPy
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import pandas as pd
c = pd.read_csv('price_dataset10k.csv')
c = c.ix[random.sample(c.index, 4000)]
#east, north, time, education -> price
training_inputs = np.vstack([c['easting'].values,c['northing'].values]).T#,c['seconds'].values,(c['QS501EW_6']/c['QS501EW_0']).values]).T
#training_inputs = training_inputs[:,0:3]
ys = c['price'].values

Xtest, free_inputs, step = dp4gp.compute_Xtest(training_inputs,steps=4)

In [15]:
Xtest.shape

(16, 2)

In [16]:
X = training_inputs

In [17]:
Xtest

array([[ 473809.2,  120088.3],
       [ 473809.2,  150063.4],
       [ 473809.2,  180038.5],
       [ 473809.2,  210013.6],
       [ 502761.6,  120088.3],
       [ 502761.6,  150063.4],
       [ 502761.6,  180038.5],
       [ 502761.6,  210013.6],
       [ 531714. ,  120088.3],
       [ 531714. ,  150063.4],
       [ 531714. ,  180038.5],
       [ 531714. ,  210013.6],
       [ 560666.4,  120088.3],
       [ 560666.4,  150063.4],
       [ 560666.4,  180038.5],
       [ 560666.4,  210013.6]])

In [23]:
X[:,0].shape

(4000,)

In [24]:
Xtest[:,0].shape

(16,)

In [33]:
np.repeat(X[:,0][:,None],Xtest.shape[0],1)

(4000, 16)

In [38]:
np.repeat(X[:,idx][:,None],Xtest.shape[0],1) > np.repeat(Xtest[:,idx][:,None],X.shape[0],1).T

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       ..., 
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]], dtype=bool)

In [21]:
X>Xtest[0,0]

array([[ True, False],
       [ True, False],
       [ True, False],
       ..., 
       [ True, False],
       [ True, False],
       [ True, False]], dtype=bool)