# DASK DP hyperparameter selection

Note: This notebook is intended to be run on the DASK scheduler.

The cross-validation structure is quite complicated, to explains;

- We split the data into training/test sets (normal cross-validation); for each split we want the probability of selecting each parameter configuration, and the score if that parameter selection is used.
- The probability of selecting that configuration is computed purely from the training data (to avoid peeking) [see lines 172-175 for the relevant calls]. Within each training data set two seperate calls are made to GridSearchCV. The first [line 109] gets the sensitivities of each fold/parameter-set of the SSE. The second [line 120] gets the negative SSE of each fold/parameter-set. We can then use these two to compute probabilities of selecting each parameter configuration using the exponential mechanism.
- The RMSE is computed on the same train/test splits (but in a seperate call, [on line 142]).
- At the end of the computation we are left with RMSEs and probabilities, we are then able to find the unbias expected RMSE.

### TODO

- Urgent: Forgot to include the limits of the SSE - these are required so that the DP assumptions on the sensitivity of the SSE are valid.

In [ ]:
from dask.distributed import Client
client = Client('127.0.0.1:8786')
import os
import distributed

runlist = ['pip install -U pip','sudo apt install libgl1-mesa-glx -y','conda update scipy -y','pip install git+https://github.com/sods/paramz.git','pip install git+https://github.com/SheffieldML/GPy.git','pip install git+https://github.com/lionfish0/dp4gp.git','conda install dask-searchcv -c conda-forge -y']

for item in runlist:
    print("Installing '%s' on workers..." % item)
    client.run(os.system,item)
    print("Installing '%s' on scheduler..." % item)
    client.run_on_scheduler(os.system,item)    
    #os.system(item) #if you need to install it locally too

In [2]:
from dp4gp import datasets
from dp4gp import dp4gp
from dp4gp.utils import dp_normalise, dp_unnormalise
import random
import numpy as np
import GPy
import matplotlib.pyplot as plt
from dp4gp import histogram
import pandas as pd
from dask_searchcv import GridSearchCV
#from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score # http://scikit-learn.org/stable/developers/contributing.html#estimators
from sklearn.base import BaseEstimator
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.cluster import KMeans
%matplotlib inline

#from dask.distributed import Client
#client = Client('127.0.0.1:8786')

kung = datasets.load_kung()

# This is an estimator for sklearn
class DPCloaking(BaseEstimator):
    def __init__(self, lengthscale=None, variance=None, errorlimit=None, kern=None, sensitivity=1.0, epsilon=1.0, delta=0.01, inducing=None, noisevariance=None, getxvalfoldsensitivities=False):
        """
        kern = a GPy kernel, Default: uses a default 1d RBF kernel, with default hyperparameters if not specified.
        inducing = locations of inducing points, default to None - not using inducing points.
        getxvalfoldsensitivities=False - score will return the sum-squared-error of each fold by default, but if this is set to true it will return the sensitivity caused by a perturbed point being in the train data
        errorlimit - when reporting the SSE we can set a limit on how large a single error is allowed to be.
        """
        
        self.errorlimit = errorlimit
        self.kern = kern
        self.sensitivity = sensitivity
        self.epsilon = epsilon
        self.delta = delta
        self.inducing = inducing
        self.getxvalfoldsensitivities = getxvalfoldsensitivities

        if lengthscale is not None:
            self.kern.lengthscale = lengthscale
        if variance is not None:
            self.kern.variance = variance
        if noisevariance is not None:
            self.noisevariance = noisevariance
        else:
            self.noisevariance = 1.0
        
    def fit(self, X, y, **kwargs): 

        #if self.kern is None:
        #    self.kern = GPy.kern.RBF(1.0)
            
        self.kern.lengthscale = self.lengthscale
        self.kern.variance = self.variance
        if self.inducing is None:
            self.model = GPy.models.GPRegression(X,y,self.kern,normalizer=None)
            self.model.Gaussian_noise = self.noisevariance
            self.dpgp = dp4gp.DPGP_cloaking(self.model,self.sensitivity,self.epsilon,self.delta)
        else:
            if isinstance(self.inducing, list):
                inducinglocs = self.inducing
            else:
                inducinglocs = KMeans(n_clusters=self.inducing, random_state=0).fit(X).cluster_centers_
            self.model = GPy.models.SparseGPRegression(X,y,self.kern,normalizer=None,Z=inducinglocs)
            self.model.Gaussian_noise = self.noisevariance
            self.dpgp = dp4gp.DPGP_inducing_cloaking(self.model,self.sensitivity,self.epsilon,self.delta)
        return self

    def predict(self, X, Nattempts=2, Nits=5): #todo set Nits back to a larger value (e.g. 100)
        print("."),
        ypred,_,_= self.dpgp.draw_prediction_samples(X,Nattempts=Nattempts,Nits=Nits)
        return ypred
    
    def score(self, X, y=None):
        """
        If self.getxvalfoldsensitivities is True then, this isn't the actual score.
        Instead it returns the sensitivity of the sum squared error if the perturbed
        point lies in the training data.
        
        If it's false this returns the NEGATIVE Sum Squared Error
        """
        #sum of squared errors
        
        if self.getxvalfoldsensitivities:          
            C = self.dpgp.get_C(X)
            return np.max(np.sum((self.sensitivity * C)**2,0)) #TODO: Handle normalisation
        else:
            errors = (y-self.predict(X))
            errors[errors>self.errorlimit] = self.errorlimit
            errors[errors<-self.errorlimit] = -self.errorlimit
            return -np.sum((y-self.predict(X))**2)

def getprobabilities(X,y,p_grid, cv):
    """
    getprobabilities(X,y,p_grid, cv)
    
    - X and y: Inputs and outputs
    - p_grid: grid of parameters to search over
    - cv: Number of cross-validation folds (this is different from the outer number of x-val folds)
    
    Gets the probability of picking each of the options provided by p_grid given the data in X and y.
    The algorithm is as follows:
     - Find the sensitivity of the SSE for each parameter-values
     - Find the SSE of each parameter-values
     - Find the probability of selecting those parameter-values
    """
    kern = GPy.kern.RBF(2.0,lengthscale=25.0,variance=1.0)
    errorlimit = ac_sens*4.0
   
    ####find sensitivity of the SSE (for each param combo)
    #this call gets the sensivities not the scores:
    #TODO This probably should be done locally as it's quick.
    clf = GridSearchCV(estimator=DPCloaking(sensitivity=ac_sens, inducing=4, getxvalfoldsensitivities=True, kern=kern, errorlimit=errorlimit), param_grid=p_grid, cv = cv)
    clf.fit(X,y)

    nparamcombos = len(clf.cv_results_['mean_test_score'])
    temp_sens = np.zeros([clf.cv,nparamcombos])
    for k in range(clf.cv):
        temp_sens[k,:] = clf.cv_results_['split%d_test_score' % k]
    #sensitivity of the sum squared error:
    #TODO Check this expression!
    sse_sens = ac_sens**2 + 2*ac_sens*errorlimit + ac_sens**2*np.max(np.sum(np.sort(temp_sens,axis=0)[0:clf.cv-1,:],0))

    ####find the SSE (for each param combo)
    clf = GridSearchCV(estimator=DPCloaking(sensitivity=ac_sens, inducing=4, getxvalfoldsensitivities=False, kern=kern, errorlimit=errorlimit), param_grid=p_grid, cv = cv)
    clf.fit(X,y)

    nparamcombos = len(clf.cv_results_['mean_test_score'])
    temp_scores = np.zeros([clf.cv,nparamcombos])
    for k in range(clf.cv):
        temp_scores[k,:] = clf.cv_results_['split%d_test_score' % k]
    scores = np.sum(temp_scores,0)

    ####compute the probability of selecting that param combo using the exponential mechanism
    selection_epsilon = 1
    param_probabilities = np.exp(selection_epsilon*scores / (2*sse_sens))
    param_probabilities = param_probabilities / np.sum(param_probabilities)
    
    return param_probabilities

def getscores(X,y,p_grid,cv):
    """
    Compute the negative RMSE of each of the fold/param combos
    """
    kern = GPy.kern.RBF(2.0,lengthscale=25.0,variance=1.0)

    clf = GridSearchCV(estimator=DPCloaking(sensitivity=ac_sens, inducing=4, getxvalfoldsensitivities=False, kern=kern), scoring='neg_mean_squared_error', param_grid=p_grid, cv = cv)
    clf.fit(X,y)

    nparamcombos = len(clf.cv_results_['mean_test_score'])
    scores = np.zeros([clf.cv,nparamcombos])
    for k in range(clf.cv):
        scores[k,:] = clf.cv_results_['split%d_test_score' % k]
    return scores

####Set up data and parameter search grid
sensitivity = 100.0
y,ac_sens,norm_params = dp_normalise(kung[kung[:,3]==0,0:1],sensitivity)
X = kung[kung[:,3]==0,1:3]
epsilon = 1.0
delta = 0.01
cv = 3
p_grid = {"lengthscale":[], 'variance':[]}#, 'noisevariance':[]}
for ls in 5.0**np.arange(0,2):
    p_grid["lengthscale"].append(ls)
for v in 5.0**np.arange(-1,1):
    p_grid["variance"].append(v)
    
####Get the -RMSE for each fold/param-combo
scores = getscores(X,y,p_grid,cv)

from sklearn.model_selection import KFold


kf = KFold(n_splits=cv)
probabilities = []
for train_index, test_index in kf.split(X):
    X_train = X[train_index]
    y_train = y[train_index]
    probabilities.append(getprobabilities(X_train,y_train,p_grid,5))
    
print(np.array(probabilities))
print(scores)
print(np.sum(probabilities*-scores,1))
print(np.mean(-scores,1))

.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.
..

.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


..



 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
..

.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log


.
.
.


 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:343: RuntimeWarning:divide by zero encountered in log
 /home/mike/Documents/Research/dp4gp/dp4gp/dp4gp.py:418: RuntimeWarning:covariance is not positive-semidefinite.


.
.
.
.
.
.
.
.
[[ 0.2780088   0.2651039   0.25994567  0.19694163]
 [ 0.26712682  0.23700197  0.31964679  0.17622442]
 [ 0.30261986  0.27097601  0.26606621  0.16033791]]
[[-0.60348814 -0.50939675 -0.65877968 -0.27725199]
 [-0.65522194 -0.95756242 -0.58511046 -0.98094521]
 [-1.8343872  -1.9017283  -1.55337318 -2.03818546]]
[ 0.52866746  0.76186672  1.81054328]
[ 0.51222914  0.79471001  1.83191854]


In [3]:
scores

array([[-0.60348814, -0.50939675, -0.65877968, -0.27725199],
       [-0.65522194, -0.95756242, -0.58511046, -0.98094521],
       [-1.8343872 , -1.9017283 , -1.55337318, -2.03818546]])

In [4]:
probabilities

[array([ 0.2780088 ,  0.2651039 ,  0.25994567,  0.19694163]),
 array([ 0.26712682,  0.23700197,  0.31964679,  0.17622442]),
 array([ 0.30261986,  0.27097601,  0.26606621,  0.16033791])]